### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by Leryan** [expectedsh/go-sonic#7]
**Edit:** figured out the google pubsub library uses goroutines for each event handling, and the driver isn't thread safe. Fixed that using channels.

Suggestion: add a documentation entry, eventually with channel usage example, to tell about that? I can make a PR if you're interested.

==============

I have this strange crash while using a Push() loop:

```
panic: runtime error: slice bounds out of range [8:6]

goroutine 131 [running]:
bufio.(*Reader).ReadSlice(0xc00005b020, 0x44760a, 0x96, 0x8, 0xc0000e3a68, 0x4cae88, 0x0)
        /usr/local/go/src/bufio/bufio.go:334 +0x22d
bufio.(*Reader).ReadLine(0xc00005b020, 0x96, 0xa0, 0x96, 0x0, 0x0, 0xc000464776)
        /usr/local/go/src/bufio/bufio.go:388 +0x34
github.com/expectedsh/go-sonic/sonic.(*connection).read(0xc0000ce990, 0xc0004646e0, 0x96, 0xa0, 0x96)
        /go/pkg/mod/github.com/expectedsh/go-sonic@v0.0.0-20190918155922-c735f46ecbcd/sonic/connection.go:52 +0x76
github.com/expectedsh/go-sonic/sonic.ingesterChannel.Push(0xc000064f80, 0xa56b94, 0x8, 0xa56b94, 0x8, 0xc000027320, 0x24, 0xc000367f80, 0x56, 0xc0000ee790, ...)
        /go/pkg/mod/github.com/expectedsh/go-sonic@v0.0.0-20190918155922-c735f46ecbcd/sonic/ingester.go:122 +0x351
REDACTED/be/services/implementation/search-ingestion.git/pkg/provider/sonic.(*ingest).Shipment(0xc000064f40, 0xc0002a5a00, 0x8, 0xc00051ee00)
        /go/src/pkg/provider/sonic/init.go:61 +0x14a
main.(*svc).handleSearchIngestEvent(0xc00008ed80, 0xb22c40, 0xc0000655c0, 0xc00021cfc0)
        /go/src/cmd/service/main.go:66 +0x32e
cloud.google.com/go/pubsub.(*Subscription).receive.func3(0xc00002d0d0, 0xc0001f8b60, 0xb22c40, 0xc0000655c0, 0xc00021cfc0)
        /go/pkg/mod/cloud.google.com/go@v0.38.0/pubsub/subscription.go:575 +0x7b
created by cloud.google.com/go/pubsub.(*Subscription).receive
        /go/pkg/mod/cloud.google.com/go@v0.38.0/pubsub/subscription.go:573 +0x221
```

I don't use BulkPush for now as i receive events from a queue.

**Comment by Leryan** [comment]
Haaa. Wait, seems pubsub is launching goroutines and i doubt the driver is thread safe, correct?

**Comment by Leryan** [comment]
Figured out the google pubsub library uses goroutines for each event handling, and the driver isn't thread safe. Fixed that using channels.

Suggestion: add a documentation entry, eventually with channel usage example, to tell about that? I can make a PR if you're interested.

**Comment by alexisvisco** [comment]
You can do a PR, I will review it when it is finished.

**Comment by Leryan** [comment]
done, see attached pr ;)
